const list = [
    "Caught sniffing glue",
    "Died (rule 2 no dying)",
    "Replied to a reddit comment without upvoting it first",
    "Has a voat account",
    "Walks too slow",
    "Owns a fedora (rule 3 no fedoras)",
    "Saying pineapple on a pizza is okay",
    "Producing too much salt",
    "Texting while driving (rule 4 no idiots)",
    "Disrespecting the Queen",
    "VAC banned from a secure server",
    "Rule 69",
    "Rule 420",
    "Non-Christian discussion (rule 5 this is a christian server)",
    "Posting your nudes in #general",
    "Because fuck you that's why",
    "😂😂😂",
    "🖕🖕🔥😤🔥🖕🖕",
    "Wearing socks with sandals",
    "Using white theme on discord",
    "Didn't come through",
    "Posting an old meme (please keep up)",
    "Tried to ford the river but died of dystenary first",
    "RSVP'd to a meetup and ghosted it",
    "Abusing !tldr",
    "Banished to Mankato",
    "Doesn't smell what The Rock is cooking.",
    "Never attending any meetups.",
    "Going for a run in Nike slides",
    "Because 🖕 that's why",
    "🖕 and a warm internet hello to you too 🖕",
    "said a bad word (This is a christian server)",
    "Using too many emoji",
    "Coughing directly on someone else",
    "Previous ban from club penguin detected and carried over [AUTOMATED EF-VAC-9521]",
    "Bullying another user until they leave",
    "I think we all know what they were doing when driving the ice cream truck",
    "DMing the new person because they had a female avatar",
    "u suck",
    "Disagreed with Vinlam",
    "Lost in High Stakes Uno",
    "Didn't stack a +2 Card in Uno",
    "Kicked a goose",
    "Gave Comic's cat bad vibes",
    "Won't shut up about pineapple on pizza",
    "Didn't say Good Morning to Pink"
];

export default {
    getReason() {
        return  list[Math.floor(Math.random()*list.length)];
    }
}
